import { v4 as uuid } from 'https://jspm.dev/uuid';

const products = [
  {
    _id: uuid(),
    name: "Acer Nitro 5 (17\")",
    img: "assets/img1.jpg",
    alt: "Acer Nitro 5 17-inch Gaming Laptop",
    brand: "Acer",
    oldprice: 141900,
    discount: 22,
    price: 110499,
    rating: 4.5,
    idealFor: "Gaming"
  },
  {
    _id: uuid(),
    name: "Acer Nitro V 15 (RTX 4050)",
    img: "assets/img2.jpg",
    alt: "Acer Nitro V 15 Gaming Laptop RTX 4050",
    brand: "Acer",
    oldprice: 130499,
    discount: 15,
    price: 110499,
    rating: 4.6,
    idealFor: "Content Creation"
  },
  {
    _id: uuid(),
    name: "Dell XPS 13 (2024)",
    img: "assets/img3.jpg",
    alt: "Dell XPS 13 Snapdragon X Elite",
    brand: "Dell",
    oldprice: 233999,
    discount: 22,
    price: 181999,
    rating: 4.4,
    idealFor: "Coding"
  },
  {
    _id: uuid(),
    name: "HP Omen Transcend 14",
    img: "assets/img4.jpg",
    alt: "HP Omen Transcend 14 Gaming Laptop",
    brand: "HP",
    oldprice: 209646,
    discount: 10,
    price: 188646,
    rating: 4.6,
    idealFor: "Multitasking"
  },
  {
    _id: uuid(),
    name: "Lenovo Legion Pro 7i",
    img: "assets/img5.jpg",
    alt: "Lenovo Legion Pro 7i Gaming Laptop",
    brand: "Lenovo",
    oldprice: 287283,
    discount: 10,
    price: 257283,
    rating: 4.7,
    idealFor: "Video Editing"
  },
  {
    _id: uuid(),
    name: "Asus ROG Strix Scar 18",
    img: "assets/img6.jpg",
    alt: "Asus ROG Strix Scar 18 Gaming Laptop",
    brand: "Asus",
    oldprice: 322383,
    discount: 9,
    price: 292383,
    rating: 4.8,
    idealFor: "Streaming"
  },
  {
    _id: uuid(),
    name: "MacBook Air M2",
    img: "assets/img7.jpg",
    alt: "Apple MacBook Air M2",
    brand: "Apple",
    oldprice: 139297,
    discount: 11,
    price: 124297,
    rating: 4.7,
    idealFor: "Students"
  },
  {
    _id: uuid(),
    name: "MacBook Pro M2",
    img: "assets/img8.jpg",
    alt: "Apple MacBook Pro M2",
    brand: "Apple",
    oldprice: 258883,
    discount: 10,
    price: 233883,
    rating: 4.8,
    idealFor: "Design"
  },
  {
    _id: uuid(),
    name: "MSI Katana GF66",
    img: "assets/img9.jpg",
    alt: "MSI Katana GF66 Gaming Laptop",
    brand: "MSI",
    oldprice: 143583,
    discount: 10,
    price: 128583,
    rating: 4.4,
    idealFor: "Streaming"
  },
  {
    _id: uuid(),
    name: "Razer Blade 15",
    img: "assets/img10.jpg",
    alt: "Razer Blade 15 Gaming Laptop",
    brand: "Razer",
    oldprice: 298927,
    discount: 5,
    price: 283927,
    rating: 4.8,
    idealFor: "Video Editing"
  },
  {
    _id: uuid(),
    name: "Dell G15 Ryzen Edition",
    img: "assets/img11.jpg",
    alt: "Dell G15 Ryzen Gaming Laptop",
    brand: "Dell",
    oldprice: 158539,
    discount: 9,
    price: 143539,
    rating: 4.5,
    idealFor: "Gaming"
  },
  {
    _id: uuid(),
    name: "Asus TUF Gaming F15",
    img: "assets/img12.jpg",
    alt: "Asus TUF Gaming F15",
    brand: "Asus",
    oldprice: 136440,
    discount: 11,
    price: 121440,
    rating: 4.5,
    idealFor: "Durability"
  },
  {
    _id: uuid(),
    name: "ThinkPad X1 Carbon",
    img: "assets/img13.jpg",
    alt: "Lenovo ThinkPad X1 Carbon",
    brand: "Lenovo",
    oldprice: 184537,
    discount: 8,
    price: 169537,
    rating: 4.6,
    idealFor: "Business"
  },
  {
    _id: uuid(),
    name: "Microsoft Surface Laptop 5",
    img: "assets/img14.jpg",
    alt: "Microsoft Surface Laptop 5",
    brand: "Microsoft",
    oldprice: 155283,
    discount: 10,
    price: 140283,
    rating: 4.4,
    idealFor: "Office Work"
  },
  {
    _id: uuid(),
    name: "HP Pavilion x360",
    img: "assets/img15.jpg",
    alt: "HP Pavilion x360 Convertible Laptop",
    brand: "HP",
    oldprice: 114333,
    discount: 13,
    price: 99333,
    rating: 4.3,
    idealFor: "Entertainment"
  },
  {
    _id: uuid(),
    name: "Samsung Galaxy Book 3",
    img: "assets/img16.jpg",
    alt: "Samsung Galaxy Book 3",
    brand: "Samsung",
    oldprice: 131883,
    discount: 11,
    price: 116883,
    rating: 4.3,
    idealFor: "Office Use"
  },
  {
    _id: uuid(),
    name: "Acer Swift 3",
    img: "assets/img17.jpg",
    alt: "Acer Swift 3 Laptop",
    brand: "Acer",
    oldprice: 103290,
    discount: 15,
    price: 88290,
    rating: 4.2,
    idealFor: "Portability"
  },
  {
    _id: uuid(),
    name: "Asus Vivobook 15",
    img: "assets/img18.jpg",
    alt: "Asus Vivobook 15",
    brand: "Asus",
    oldprice: 90933,
    discount: 17,
    price: 75933,
    rating: 4.2,
    idealFor: "Students"
  },
  {
    _id: uuid(),
    name: "HP Envy 13",
    img: "assets/img19.jpg",
    alt: "HP Envy 13 Ultrabook",
    brand: "HP",
    oldprice: 119865,
    discount: 13,
    price: 104865,
    rating: 4.3,
    idealFor: "Office Use"
  },
  {
    _id: uuid(),
    name: "Lenovo IdeaPad Slim 5",
    img: "assets/img20.jpg",
    alt: "Lenovo IdeaPad Slim 5",
    brand: "Lenovo",
    oldprice: 106306,
    discount: 14,
    price: 91306,
    rating: 4.4,
    idealFor: "Multitasking"
  }
];

export default products;
